// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlK1X7MBVejzYDiQOHY-MvVQKZc22gl8',
    appId: '1:341024830914:web:3b4bacd6ece056f819d25b',
    messagingSenderId: '341024830914',
    projectId: 'tubes-monitoring-udara',
    authDomain: 'tubes-monitoring-udara.firebaseapp.com',
    storageBucket: 'tubes-monitoring-udara.appspot.com',
    measurementId: 'G-PP51K5258Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-HyOemFUJjDpcgMW4PIRvExxo32F6sg',
    appId: '1:341024830914:android:8d62367cafe219fa19d25b',
    messagingSenderId: '341024830914',
    projectId: 'tubes-monitoring-udara',
    storageBucket: 'tubes-monitoring-udara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZcJjMrzmFff2zuP4_vBUn5NRlQpTlnEw',
    appId: '1:341024830914:ios:df83ebbf83aa9ac019d25b',
    messagingSenderId: '341024830914',
    projectId: 'tubes-monitoring-udara',
    storageBucket: 'tubes-monitoring-udara.appspot.com',
    iosClientId:
        '341024830914-9qudn3s1ks5hsgv4as1das9sga326ege.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringKualitasUdara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZcJjMrzmFff2zuP4_vBUn5NRlQpTlnEw',
    appId: '1:341024830914:ios:df83ebbf83aa9ac019d25b',
    messagingSenderId: '341024830914',
    projectId: 'tubes-monitoring-udara',
    storageBucket: 'tubes-monitoring-udara.appspot.com',
    iosClientId:
        '341024830914-9qudn3s1ks5hsgv4as1das9sga326ege.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringKualitasUdara',
  );
}
